name: JS Models Build & Test

on: pull_request

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: NPM install
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Run NPM CI
              run: npm ci

            - name: Run Lerna Bootstrap
              run: npm run bootstrap

            - name: Lint with ESLint
              run: npm run lint

            - name: Build Files
              run: npm run build

            - name: Run Core tests
              run: npm run test

            - name: Archive npm failure logs
              uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: npm-logs
                path: ~/.npm/_logs
